on: push
name: 🚀 Deploy forms on push
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_EMAILS_TO: ${{ secrets.EMAILS_TO }}
          envkey_EMAILS_CC: ${{ secrets.EMAILS_CC }}
          envkey_EMAILS_FROM: ${{ secrets.EMAILS_FROM }}
          envkey_EMAILS_FROM_PASSWORD: ${{ secrets.EMAILS_FROM_PASSWORD }}
          envkey_G_RECAPTCHA_SECRET: ${{ secrets.G_RECAPTCHA_SECRET }}
          envkey_TEST: This_helps_me_to_check_if_ghaction_worked
          directory: src
          fail_on_empty: true
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: ls
        run: ls -la
      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: james-wilson.dreamhost.com
          remote-user: dh_y3sar9
          private-ssh-key: ${{ secrets.PRIVATE_KEY }}
          destination-path: ~/cms.manhattanmanor.com/forms/
